/**
 * Local WordPress for development and verification.
 *
 * Runs WordPress on PHP's built-in server against SQLite, so there is no Docker
 * and no MySQL to install. Everything lands in .wp/ which is gitignored — the
 * repo only ever contains the theme and the plugin.
 *
 *   npm run wp:start   download if needed, install, symlink, serve
 *   npm run wp:stop    stop the server
 *   npm run wp:reset   delete .wp and start over
 *
 * Usage: node tools/wp-dev.mjs <start|stop|reset>
 */
import { spawn, execFileSync } from 'node:child_process';
import {
	existsSync,
	mkdirSync,
	rmSync,
	writeFileSync,
	readFileSync,
	symlinkSync,
	copyFileSync,
	unlinkSync,
	lstatSync,
} from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const wpDir = join(root, '.wp');
const core = join(wpDir, 'wordpress');
const content = join(core, 'wp-content');
const cli = join(wpDir, 'wp-cli.phar');
const pidFile = join(wpDir, 'server.pid');

const PORT = process.env.SPCS_PORT || '8765';
const URL = `http://localhost:${PORT}`;

const run = (cmd, args, opts = {}) =>
	execFileSync(cmd, args, { stdio: 'inherit', cwd: root, ...opts });

const wp = (args) =>
	run('php', [cli, `--path=${core}`, ...args, '--skip-plugins=akismet,hello']);

const log = (msg) => console.log(`\n▸ ${msg}`);

/* ── Download ─────────────────────────────────────────────────────────── */

function download() {
	mkdirSync(wpDir, { recursive: true });

	if (!existsSync(core)) {
		log('Downloading WordPress core');
		run('curl', ['-fsSL', '-o', join(wpDir, 'wp.tar.gz'), 'https://wordpress.org/latest.tar.gz']);
		run('tar', ['-xzf', join(wpDir, 'wp.tar.gz'), '-C', wpDir]);
		rmSync(join(wpDir, 'wp.tar.gz'));
	}

	if (!existsSync(cli)) {
		log('Downloading WP-CLI');
		run('curl', [
			'-fsSL',
			'-o',
			cli,
			'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar',
		]);
	}

	const sqlite = join(content, 'plugins', 'sqlite-database-integration');

	if (!existsSync(sqlite)) {
		log('Downloading the SQLite database integration plugin');
		const zip = join(wpDir, 'sqlite.zip');
		run('curl', [
			'-fsSL',
			'-o',
			zip,
			'https://downloads.wordpress.org/plugin/sqlite-database-integration.zip',
		]);
		run('unzip', ['-q', '-o', zip, '-d', join(content, 'plugins')]);
		rmSync(zip);
	}

	// The SQLite plugin ships its drop-in as db.copy with a path placeholder.
	const dropIn = join(content, 'db.php');
	if (!existsSync(dropIn)) {
		const template = readFileSync(join(sqlite, 'db.copy'), 'utf8')
			.replace("'{SQLITE_IMPLEMENTATION_FOLDER_PATH}'", `'${sqlite}'`)
			.replace('{SQLITE_PLUGIN}', 'sqlite-database-integration/load.php');
		writeFileSync(dropIn, template);
	}
}

/* ── Configure ────────────────────────────────────────────────────────── */

function configure() {
	const configPath = join(core, 'wp-config.php');

	if (existsSync(configPath)) return;

	log('Writing wp-config.php');

	const salts = Array.from({ length: 8 }, () =>
		Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2)
	);
	const keys = [
		'AUTH_KEY',
		'SECURE_AUTH_KEY',
		'LOGGED_IN_KEY',
		'NONCE_KEY',
		'AUTH_SALT',
		'SECURE_AUTH_SALT',
		'LOGGED_IN_SALT',
		'NONCE_SALT',
	];

	writeFileSync(
		configPath,
		`<?php
/** Local development only. Generated by tools/wp-dev.mjs — not for production. */
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', '' );
define( 'DB_PASSWORD', '' );
define( 'DB_HOST', '' );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );

${keys.map((key, index) => `define( '${key}', '${salts[index]}' );`).join('\n')}

/*
 * Pinned because core lives in .wp/wordpress while the router serves it from
 * the domain root — without these WordPress infers a /wordpress/ subdirectory
 * and 301s every request to it.
 */
define( 'WP_HOME', '${URL}' );
define( 'WP_SITEURL', '${URL}' );

$table_prefix = 'wp_';

define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
define( 'SCRIPT_DEBUG', true );
define( 'WP_ENVIRONMENT_TYPE', 'local' );

/*
 * Without this WordPress caches the pattern and template-part file headers, so
 * a newly added or renamed pattern file silently never registers.
 */
define( 'WP_DEVELOPMENT_MODE', 'all' );
define( 'DISALLOW_FILE_EDIT', true );
define( 'AUTOMATIC_UPDATER_DISABLED', true );

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
`
	);
}

/* ── Link the theme and plugin ────────────────────────────────────────── */

function link() {
	const links = [
		[join(root, 'themes', 'spcs'), join(content, 'themes', 'spcs')],
		[join(root, 'plugins', 'spcs-core'), join(content, 'plugins', 'spcs-core')],
	];

	for (const [from, to] of links) {
		// Replace an existing link so a moved checkout doesn't leave a dangling one.
		try {
			if (lstatSync(to)) unlinkSync(to);
		} catch {
			/* not present, nothing to remove */
		}
		symlinkSync(from, to, 'dir');
	}
}

/* ── Install ──────────────────────────────────────────────────────────── */

function install() {
	const installed = (() => {
		try {
			execFileSync('php', [cli, `--path=${core}`, 'core', 'is-installed'], {
				stdio: 'ignore',
			});
			return true;
		} catch {
			return false;
		}
	})();

	if (!installed) {
		log('Installing WordPress');
		wp([
			'core',
			'install',
			`--url=${URL}`,
			'--title=SPCS Gatekeepers',
			'--admin_user=admin',
			'--admin_password=admin',
			'--admin_email=dev@spcsprogram.org',
			'--skip-email',
		]);
	}

	log('Activating theme and plugin');
	wp(['theme', 'activate', 'spcs']);
	wp(['plugin', 'activate', 'spcs-core']);

	// Pretty permalinks — the nav links are all path-based.
	wp(['rewrite', 'structure', '/%postname%/']);
	wp(['rewrite', 'flush', '--hard']);
}

/* ── Server ───────────────────────────────────────────────────────────── */

function start() {
	stop({ quiet: true });

	log(`Serving ${URL}`);

	const child = spawn(
		'php',
		['-S', `localhost:${PORT}`, '-t', core, join(root, 'tools', 'router.php')],
		{ detached: true, stdio: ['ignore', 'ignore', 'ignore'] }
	);

	child.unref();
	writeFileSync(pidFile, String(child.pid));

	console.log(`
  Site       ${URL}
  Admin      ${URL}/wp-admin  (admin / admin)
  Site editor ${URL}/wp-admin/site-editor.php

  Stop with: npm run wp:stop
`);
}

function stop({ quiet = false } = {}) {
	if (!existsSync(pidFile)) {
		if (!quiet) console.log('No server running.');
		return;
	}

	const pid = Number(readFileSync(pidFile, 'utf8').trim());

	try {
		process.kill(pid);
		if (!quiet) console.log(`Stopped PHP server (pid ${pid}).`);
	} catch {
		/* already gone */
	}

	rmSync(pidFile, { force: true });
}

/* ── Entry point ──────────────────────────────────────────────────────── */

const command = process.argv[2] || 'start';

if (command === 'stop') {
	stop();
} else if (command === 'reset') {
	stop({ quiet: true });
	rmSync(wpDir, { recursive: true, force: true });
	console.log('Removed .wp — run npm run wp:start to rebuild it.');
} else {
	download();
	configure();
	link();
	install();
	start();
}
